name: build-and-push-azure-vote-to-acr

# Run this workflow every time a new commit pushed to your repository
on: 
  push:
    branches:
      - main
    paths:
      - azure-vote/**

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build-docker:
    # Name the Job
    name: build docker job name
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - 
        name: Checkout code
        uses: actions/checkout@v2
      - 
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.acr_server }}
          username: ${{ secrets.acr_username }}
          password: ${{ secrets.acr_password }}

      - 
        run: |
          docker build ./azure-vote -t ${{ secrets.acr_server }}/azure-vote-aks-test:${{ github.sha }}
          docker push ${{ secrets.acr_server }}/azure-vote-aks-test:${{ github.sha }}
      
